### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by esafeddie** [0xCUB3/About-This-Hack#11]
Got popup message for latest update 0.6.0 now available but after download, at the beginning of the installation an error message shows as 'Update Error' with the only option to cancel. Version 0.5.0 works fine.
![Screenshot 2023-01-18 at 21 11 59](https://user-images.githubusercontent.com/7919587/213295952-f29227d1-b728-4b7f-9c88-82d4393da13d.png)
![Screenshot 2023-01-18 at 21 13 07](https://user-images.githubusercontent.com/7919587/213295965-29a619d1-53c1-4c09-9dcf-40b2f84a3d2b.png)

**Comment by 0xCUB3** [comment]
yeah this happens to some people. Uninstall the app you have now and download the latest version. Sorry about that!
