### ISSUE TITLE
[Feature Request] Add Model Identifier

### ISSUE THREAD

**Issue by JayMonkey** [0xCUB3/About-This-Hack#12]
Hi,

Great little app, how about adding the SMBIOS model Identifier to the first line ?

For example my Z490 system is using iMac20,2 : - 
![Mock-Up](https://user-images.githubusercontent.com/5662056/214890688-0981704e-1e22-4ea6-96eb-5d0f4ac0f955.png)
One slight quibble is the app seems to take a long time to open (icon bouncing in dock for around 20 seconds)
Other than that it runs and looks great.

Cheers
Jay

**Comment by 0xCUB3** [comment]
Hello Jay,

Thanks for the feedback! I like your idea about adding the model identifier, but that might take up too much space. What do you think of functionality that would toggle between the iMac 27-inch (blah blah blah) and the model id when clicked? 

> One slight quibble is the app seems to take a long time to open (icon bouncing in dock for around 20 seconds). Other than that it runs and looks great.

Yeah this is something I'm trying to figure out. Since the app requires running terminal commands, it takes awhile to load. That is definitely on the list for v1.0.0.

**Comment by matxpa** [comment]
Hi 0xCUB3

Like this with SMBios, Bootloader OC or Clover and "System Report ..." "Software Update ..." buttons


![Capture d’écran 2023-02-04 à 16 52 13](https://user-images.githubusercontent.com/70573409/216777046-817fedf9-6a93-40ed-8335-e9b28517d3c8.png)

Regards
matxpa

**Comment by 0xCUB3** [comment]
I already have something like that but for the OpenCore version, appearing only if the user has opencore installed. I don't know how to access version data in Clover as I don't have a machine that runs it, but I would love to add it. Could you put that into code and create a PR since you have a computer with clover?

Also for the system report thing, I agree that it's a good idea! I can implement it in the next update or some update in the future.

**Comment by JayMonkey** [comment]
> Also for the system report thing, I agree that it's a good idea! I can implement it in the next update or some update in the future.

+1 for adding the System Report (System Information) button, Apple removed that from ATM in Ventura which i know many (including myself) found annoying.

**Comment by 0xCUB3** [comment]
good to know. I'll add those in the next release.

**Comment by matxpa** [comment]
Hi
Only 3 modified components
1) Base.lproj/Main.storyboard
2) HardwareCollector.swift
3) ViewController.swift

3 files attached, i don't want make a fork, cause it's your bab'
[About-This-Hack Vn (n is what you'l want).zip](https://github.com/0xCUB3/About-This-Hack/files/10609252/About-This-Hack.Vn.n.is.what.you.l.want.zip)
(surly you know "SourceGear DiffMerge" so you'l choose and retain all or part of the modifications)

On a Laptop Lenovo Thinkpad T550 (Broadwell) with OC (with Monterey too)
![Capture d’écran 2023-02-04 à 18 51 06](https://user-images.githubusercontent.com/70573409/216782318-3c5cfbb7-b223-452b-8858-819af1239799.png)

On a Laptop Asus X75VB (Ivy Bridge) with Clover (with Ventura too)
![Capture d’écran 2023-02-04 à 16 52 13](https://user-images.githubusercontent.com/70573409/216782622-308e1577-463f-49d7-ae4e-f89348aed46c.png)

Regards
matxpa

**Comment by 0xCUB3** [comment]
Thanks a lot! I will add it when I have some time. Your contributions are very much appreciated since this is such a small project (and my first one with any publicity!)

**Comment by matxpa** [comment]
If you wana test your modified "app" (attached in the attached "zip" file)

[About This Hack.app.zip](https://github.com/0xCUB3/About-This-Hack/files/10609345/About.This.Hack.app.zip)

Regards
matxpa

**Comment by 0xCUB3** [comment]
thanks! This also reminds me that I need to add the newly-released macs to the list of model IDs. 
![image](https://user-images.githubusercontent.com/94565160/216783071-c3e0ec3f-9d83-48e4-9f4e-41bd3edb9707.png)

**Comment by JayMonkey** [comment]
> If you wana test your modified "app" (attached in the attached "zip" file)

@0xCUB3, @matxpa,

Just tried @matxpa's test version on my HP X360 laptop, looks good.
Liking the new buttons for System Report and Software Update.
<img width="692" alt="Screenshot 2023-02-04 at 18 37 37" src="https://user-images.githubusercontent.com/5662056/216784176-f32032b0-8cbb-4399-9ceb-19893a79a464.png">
Cheers
Jay

**Comment by 0xCUB3** [comment]
@JayMonkey @matxpa could you test this build to see if the OpenCore and Clover bootloaders are showing up properly? I don't have a hackintosh anymore so I can't test. If you could send some screenshots too, that would be greatly appreciated.

Here's what the two new buttons look like:
![image](https://user-images.githubusercontent.com/94565160/216837226-a0b8ace9-9374-4da9-84d1-91f5aba310ad.png)

Build:
[About This Hack.zip](https://github.com/0xCUB3/About-This-Hack/files/10611798/About.This.Hack.zip)

**Comment by JayMonkey** [comment]
> @JayMonkey @matxpa could you test this build to see if the OpenCore and Clover bootloaders are showing up properly? I don't have a hackintosh anymore so I can't test. If you could send some screenshots too, that would be greatly 

@0xCUB3,

Test build run on my HP Laptop Hack, buttons and open core version detected, however the term OpenCore Version is repeated ?
<img width="692" alt="Screenshot 2023-02-06 at 00 02 29" src="https://user-images.githubusercontent.com/5662056/216854121-6adda0b1-8438-4039-af17-e2230f97da30.png">
I will run a test on my Desktop hack tomorrow and post a screenshot.

Cheers
Jay

**Comment by 0xCUB3** [comment]
@JayMonkey oh yeah haha I forgot to change the bold text to "bootloader". Glad to see that it's working though!

@matxpa could you test the build on Clover? Ignore the fact that it will say OpenCore Version for now

**Comment by JayMonkey** [comment]
@0xCUB3,

Screen grab on my Z490 Desktop hackintosh as promised : -
![Screenshot 2023-02-06 at 14 42 46](https://user-images.githubusercontent.com/5662056/217002055-37823ee1-f993-465d-8ac7-ebdc14169e74.png)
Cheers
Jay

**Comment by matxpa** [comment]
@matxpa could you test the build on Clover? Ignore the fact that it will say OpenCore Version for now

Your latest build tested with Clover

![About this Hack (your latest test version)](https://user-images.githubusercontent.com/70573409/217043300-0ccfcc77-8fa0-4fd2-bbe6-b58b82c10890.png)

And Now My latest one (reduced OS Icon size and increased display areas size)
with Clover
![About this Hack (my new version)](https://user-images.githubusercontent.com/70573409/217039888-32fde043-007b-4ce5-b50c-5adc6d18931e.png)

and now with OpenCore
![About this Hack Z270 Ventura](https://user-images.githubusercontent.com/70573409/217042039-9b461104-9cbb-411a-87a3-5183f52a9523.png)

And Apple version to compare
![About this Mac (Apple one)](https://user-images.githubusercontent.com/70573409/217041056-23234e70-2489-4104-81be-6c4b56fe9998.png)

**Comment by 0xCUB3** [comment]
Thanks guys! The latest commit fixes all the text issues.

**Comment by JayMonkey** [comment]
@0xCUB3,

Happy to test latest commit ..
I don't currently have Xcode installed on this machine, can you post test App  here ?

**Comment by 0xCUB3** [comment]
@JayMonkey ah that's ok, there's no need to test. I had someone at school test it for me. Thanks for all the help! The changes will be added to the next release.

**Comment by JayMonkey** [comment]
@0xCUB3,

Ok no problem, look forward to the next release ....

**Comment by matxpa** [comment]
@0xCUB3 @JayMonkey 

Hi
An other one with "Kernel Version"

![Capture d’écran 2023-02-08 à 10 35 46](https://user-images.githubusercontent.com/70573409/217498816-4ab75f84-c463-4e8f-9dcb-c61312fc0d4b.png)

Regards
matxpa

**Comment by matxpa** [comment]
@0xCUB3

As you've already done on HardwareCollector.swift with
	...
        _ = graphicsArray.count in  "static func getGPU() -> String {" code
	...
(_ =) to avoid the warning message "Result of call to 'run' is unused" on

ViewController.swift
...
@IBAction func showSystemReport(_ sender: NSButton) {
        print("System Report...")
        _ = run("open /System/Library/SystemProfiler/SPPlatformReporter.spreporter")
    }

    @IBAction func showSoftwareUpdate(_ sender: NSButton) {
        print("Software Update...")
        _ = run("open /System/Library/PreferencePanes/SoftwareUpdate.prefPane")
    }
...


ViewControllerDisplays.swift
...
    @IBAction func openPrefsDispl(_ sender: Any) {
        _ = run("open /System/Library/PreferencePanes/Displays.prefPane")
    }
...


And to show SMBios (if you want) at the end off "macName" in
HardwareCollector.swift
...
        queue.async {
            macName = getMacName()
            macName += " \(infoString)"  (but infoString must be a static var)
            print("Mac name: \(macName)")

    static func getMacName() -> String {
        // from https://everymac.com/systems/by_capability/mac-specs-by-machine-model-machine-id.html
        let infoString = run("sysctl hw.model | cut -f2 -d \" \" | tr -d '\n'")
        switch(infoString) {

Regards
matxpa

**Comment by 0xCUB3** [comment]
Thanks a lot! I'll add these to the next commit when I have time.

**Comment by 0xCUB3** [comment]
Pushed the changes. I will keep the SMBIOS data out for now, though.

**Comment by matxpa** [comment]
Hi 0xCUBE

 

It’s your child so you do what you want with it

 

If you’d like to display Kernel Version and SIP (status and value) like in the attached  ScreenShot, the code is :

 

HardwareCollector.swift

 

    static func getOSBuildNum() -> String {

//        return run("system_profiler SPSoftwareDataType | grep 'System Version' | cut -c 29-")

// System Version + Kernel Version + System Integrity Protection status + csr-active-config value

 return run ("echo $(system_profiler SPSoftwareDataType | grep \"System Version:\" | awk -F':' '{print $2}' | awk '{print $2,$3,$4}' | tr -d \"\\n\") $(system_profiler SPSoftwareDataType | grep \"Kernel Version:\" | awk -F':' '{print $2}' | tr -d \"\\n\") $(system_profiler SPSoftwareDataType | grep \"System Integrity Protection:\" | awk -F':' '{print \"SIP:\"$2}' | tr -d \"\\n\") $(nvram -Xp | grep \"csr-active-config\" | awk '{print \"(\"$2\")\"}')")

    }

 

Regards

matxpa

 

De : 0xCUBE ***@***.***>
Répondre à : 0xCUB3/About-This-Hack ***@***.***>
Date : vendredi 10 février 2023 à 17:19
À : 0xCUB3/About-This-Hack ***@***.***>
Cc : Jean-Michel Meunier ***@***.***>, Mention ***@***.***>
Objet : Re: [0xCUB3/About-This-Hack] [Feature Request] Add Model Identifier (Issue #12)

 

Pushed the changes. I will keep the SMBIOS data out for now, though.

**Comment by 0xCUB3** [comment]
wow thanks! This is much appreciated.

**Comment by nocontent06** [comment]
Added btw... in release [0.9.0](https://github.com/0xCUB3/About-This-Hack/releases/tag/0.9.0)
