### ISSUE TITLE
error 0.6.0

### ISSUE THREAD

**Issue by kaoskinkae64** [0xCUB3/About-This-Hack#14]
Error when updating to version 0.6.0beta but even when downloading the previous version from the www I experience the same problem I can only use another version 0.5.0 to return to the normal state downloaded a long time ago
![Captura de pantalla 2023-02-13 a las 10 51 41](https://user-images.githubusercontent.com/73172409/218426595-ea22b250-ec53-4671-9c77-70cf61820b34.png)

**Comment by 0xCUB3** [comment]
Yeah it's a codesigning issue because I don't have a paid signing account. Your options are either to sign it yourself (if you know how to do that) or try again in a few days since it's super random (not everyone experiences crashes)

**Comment by kaoskinkae64** [comment]
It means that I compile it myself

**Comment by 0xCUB3** [comment]
@kaoskinkae64 the issues might be resolved in the latest release. Please test it if you can and report back:
https://github.com/0xCUB3/About-This-Hack/releases/tag/0.7.0
