### ISSUE TITLE
Ventura 13.2.1 flags ATH as malware. Refuses to run.

### ISSUE THREAD

**Issue by superbogie** [0xCUB3/About-This-Hack#15]
About This Hack v 0.6.0 previously ran under macOS Ventura 13.2 but after the recent update to 13.2.1, OS refuses to open ATH and now flags it as malware. Now, options are only to Move to Trash or Cancel (with an additional checkbox to Report malware to Apple to protect other users).

**Comment by WildChild-SomethingWild** [comment]
> About This Hack v 0.6.0 previously ran under macOS Ventura 13.2 but after the recent update to 13.2.1, OS refuses to open ATH and now flags it as malware. Now, options are only to Move to Trash or Cancel (with an additional checkbox to Report malware to Apple to protect other users).

Might be related to the security enhancement.

<img width="1158" alt="Capture d’écran, le 2023-02-18 à 12 43 55" src="https://user-images.githubusercontent.com/83997024/219880472-b5641789-d7ff-43af-aaea-a238dd9d028e.png">

**Comment by WildChild-SomethingWild** [comment]
It must have been revoked, this is not the first time I see this message in the past months.

**Comment by 0xCUB3** [comment]
> It must have been revoked, this is not the first time I see this message in the past months.

yeah since the app receives a lot of traffic and I don't have a paid developer account, apple revokes the app within a week. It's very annoying and I can't do anything about it other than constantly make releases (which I don't have time for). I will pin this issue so future users know the problem.

**Comment by WildChild-SomethingWild** [comment]
👍🏻

**Comment by superbogie** [comment]
👍🏻

**Comment by maverx72** [comment]
Same for me. OC 0.9.0 - Ventura 13.2.1

**Comment by 0xCUB3** [comment]
@WildChild-SomethingWild @maverx72 @superbogie the issues *might* be resolved in the latest release. Please test it if you can and report back:
https://github.com/0xCUB3/About-This-Hack/releases/latest

**Comment by superbogie** [comment]
> @WildChild-SomethingWild @maverx72 @superbogie the issues _might_ be resolved in the latest release. Please test it if you can and report back: https://github.com/0xCUB3/About-This-Hack/releases/latest

Success! After approving the app in Privacy & Security System Settings pane, ATH v0.7.0 beta works for me! Thanks for the fix and the update, @0xCUB3!
