### ISSUE TITLE
Why not using Original disk Icon?

### ISSUE THREAD

**Issue by chris1111** [0xCUB3/About-This-Hack#22]
/System/Library/Extensions/`IOStorageFamily.kext`/Contents/Resources/Internal.icns

![Screenshot 2023-03-09 at 4 27 46 PM](https://user-images.githubusercontent.com/6248794/224164312-e121730c-6ba8-48fe-8f1e-313f4d0b6550.png)
![Screenshot 2023-03-09 at 4 28 53 PM](https://user-images.githubusercontent.com/6248794/224164331-30bc2e7d-c1c0-40c7-8516-4febad74385d.png)

**Comment by 0xCUB3** [comment]
at the time of making, I was unaware of these icons as this was my first ever project in swift haha. I'll change them in the next release.
