### ISSUE TITLE
Model not recognised (MacBook Pro, Early 2008)

### ISSUE THREAD

**Issue by nocontent06** [0xCUB3/About-This-Hack#25]
![image](https://github.com/0xCUB3/About-This-Hack/assets/93335632/10732427-1be0-4b7a-9314-7c2a8fd253fc)

My MacBookPro4,1 is not implemented in your Code...
Bro there are still ppl out there who use such pretty models :)

Bye and thx for ATH2

**Comment by 0xCUB3** [comment]
My bad! I didn't think that people would patch the 4,1 all the way to Mojave 😀 

I will add older models in the next release

**Comment by nocontent06** [comment]
Haha cool!

Yeah. I patched mine to Catalina...
(Btw. ATH2 needs an Update too in this case :P)

**Comment by 0xCUB3** [comment]
About ATH2...I am in no way affiliated with that app. It's just someone I know who decided to make a spin-off of my app lol. It's good to be famous I guess 🤪

**Comment by 0xCUB3** [comment]
Resolved in latest commit
