### ISSUE TITLE
[Feature request] Add RAM infos and Memory tab

### ISSUE THREAD

**Issue by dreamwhite** [0xCUB3/About-This-Hack#3]
It would be useful to:

- display RAM type (e.g. `DDR4`) as well as their frequency (e.g. `2400MHz`). Something like this:
![image](https://user-images.githubusercontent.com/17933708/177850519-ac41ae66-c49d-488f-8e5d-0bb5bbf4a317.png)

- Memory tab:

![image](https://user-images.githubusercontent.com/17933708/177850643-99903833-37c7-43c7-bf4b-7c119341b6c1.png)

**Comment by 0xCUB3** [comment]
Yeah, we've actually been working on RAM. Unfortunately, since all the stats come from terminal commands, there isn't a simple terminal command for RAM type and speed, since they're stored differently for different Macs for some reason. I'm not sure how apple gets its data from. If you know, I'd appreciate knowing

**Comment by dreamwhite** [comment]
Hi thanks for the reply. I think you can actually base the whole app using IOKit API which is way faster than executing terminal commands

**Comment by 0xCUB3** [comment]
Really? Can you share an example of an app that uses it? I'm intrigued

**Comment by dreamwhite** [comment]
I'm not a Swift developer neither a IOKit expert but [TINU](https://github.com/ITzTravelInTime/TINU/) uses some IOKit API calls to retrieve infos such as disks and so on

**Comment by dreamwhite** [comment]
Hi @0xCUB3 any update on this issue?

**Comment by 0xCUB3** [comment]
> Hi @0xCUB3 any update on this issue?

I haven't had much time to work on the app because of the school year, but it's a feature that will be added when I get back to work on this app

**Comment by dreamwhite** [comment]
Sure, take your time. No hurry on that

**Comment by MDNich** [comment]
@dreamwhite Looking into this a bit; we will try to add another tab with memory similar to the traditional Mac one.
We will likely address primarily total memory and number of slots and what size, though the UI may be a bit difficult to replicate. 

Do you happen to know what the criteria for memory tab showing is? That way we can replicate that even more...though it's ok if not.

Thanks so much for your interest in the project! :)

**Comment by dreamwhite** [comment]
Hi! Thank you so much for giving such effort for the project. Actually the criteria should match at least the default behaviour of macOS such as depicted below:

![image](https://user-images.githubusercontent.com/17933708/213010377-8b58b5b8-ecde-4dbd-8d72-3bb682189be2.png)

where

- you should find a way to retrieve the total amount of memory and place it inside the blue box (e.g. `10 GB installed`)
- A text like `Your Mac contains N memory slots, each of which accepts a MEMORY_SPEED MHz MEMORY_TYPE memory module`
- If every memory slot is used display a text like `All memory slots are currently in use` otherwise `N_OF_USED_MEMORY_SLOTS memory slots in use, N_OF_UNUSED_MEMORY_SLOTS available` as depicted below:
![image](https://user-images.githubusercontent.com/17933708/213010871-75f5a863-30b2-45a5-bbac-34edeafc65f7.png)

**Comment by MDNich** [comment]
Ok thank you so much for that. I will have to look into how to access the number of slots nicely with @0xCUB3, and as default we will show it all the time. 
Thanks again, will keep you posted on progress.

**Comment by dreamwhite** [comment]
I don't know if you're planning to use IORegistry keys or not, but in case it becomes helpful:

```ioreg -p IODeviceTree -n memory``` gives you the necessary info to parse, such as the slot names and dimm speeds

**Comment by MDNich** [comment]
Sounds good thx!! Will probably use that.

**Comment by MDNich** [comment]
Haven't forgotten about this @dreamwhite, will work on it soon

**Comment by dreamwhite** [comment]
Good morning. Nice to hear that! I'm willing to test it whenever you want

**Comment by 0xCUB3** [comment]
For now I will close this as "will not fix". This is too big of a project for the initial stable release. I will reopen if/when I start thinking about implementing this.
