### ISSUE TITLE
Commit 9aaf8bb lack of a break in case .SONOMA: (ViewController)

### ISSUE THREAD

**Issue by matxpa** [0xCUB3/About-This-Hack#32]
Hi @0xCUB3 

In last week 9aaf8bb commit on ViewController when adding Sonoma icon
...
        // Image
        switch HardwareCollector.OSvers {
        case .SONOMA:
            picture.image = NSImage(named: "Sonoma")
        case .VENTURA:
            picture.image = NSImage(named: "Ventura")
            break
...

Regards

**Comment by 0xCUB3** [comment]
Fixed. Thanks for catching that; we're all human, after all! 🤪
