### ISSUE TITLE
OpenCore info is missing after new BootloaderInfo code

### ISSUE THREAD

**Issue by perez987** [0xCUB3/About-This-Hack#48]
Good afternoon. Great improvements in last days, the app starts very quickly, every tab is well displayed and storage info is filled also very quickly.

But I want to comment a possible issue that I have noticed with last commit `ccfac1c Move start functions`.

There have been changes in the `getBootloader` function to check if OCLP exists. Building the app as is, just downloaded from the repo, all is working well but OpenCore info is missing, next to Bootloader text.

1. With the current code in `func getBootloader`, I get no info in the Bootloader text box.
```swift
var BootloaderInfo: String = ""
        BootloaderInfo = run("nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}'")
        if BootloaderInfo != "" {
            // Regular OpenCore
            if run("grep -A1 \"OpenCore Legacy Patcher\" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.?OCLP: ?g' -e 's??, ?g'").contains("No") {
                BootloaderInfo = run("echo \"OpenCore v\" $(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}' | sed -e 's/ */./g' -e s'/^.//g' -e 's/.$//g' -e 's/ .//g' -e 's/. //g' | tr -d '\n') $( nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $1}' | sed -e 's/REL/(Release)/g' -e s'/N\\/A//g' -e 's/DEB/(Debug)/g' | tr -d '\n')")
            } else {
                BootloaderInfo = run("grep -A1 \"OpenCore Legacy Patcher\" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.?OCLP ?g' -e 's??, ?g'") + run("echo \"(OpenCore v\" $(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}' | sed -e 's/ */./g' -e s'/^.//g' -e 's/.$//g' -e 's/ .//g' -e 's/. //g' | tr -d '\n'))")
            }
        }
```
2. Commenting the code related to OCLP, leaving only the block to get OpenCore info, I get `OpenCore v 0.9.4`, no `(Release)` text at the end.
```swift
        var BootloaderInfo: String = ""
        BootloaderInfo = run("nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}'")
        if BootloaderInfo != "" {
             // Regular OpenCore
            //if run("grep -A1 \"OpenCore Legacy Patcher\" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.?OCLP: ?g' -e 's??, ?g'").contains("No") {
            BootloaderInfo = run("echo \"OpenCore v. \" $(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}' | sed -e 's/ */./g' -e s'/^.//g' -e 's/.$//g' -e 's/ .//g' -e 's/. //g' | tr -d '\n') $( nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $1}' | sed -e 's/REL/(Release)/g' -e s'/N\\/A/g' -e 's/DEB/(Debug)/g' | tr -d '\n')")
            //} else {
                //BootloaderInfo = run("grep -A1 \"OpenCore Legacy Patcher\" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.?OCLP ?g' -e 's??, ?g'") + run("echo \"(OpenCore v\" $(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}' | sed -e 's/ */./g' -e s'/^.//g' -e 's/.$//g' -e 's/ .//g' -e 's/. //g' | tr -d '\n'))")
            //}
        }
```
3. As in step 2, but replacing current `BootloaderInfo` by the previous code, before build `dd2dadf Simplify OpenCore output`, I get `OpenCore v 0.9.4 (Release)`, as expected.
```swift
        var BootloaderInfo: String = ""
        BootloaderInfo = run("nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}'")
        if BootloaderInfo != "" {
             // Regular OpenCore
            //if run("grep -A1 \"OpenCore Legacy Patcher\" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.?OCLP: ?g' -e 's??, ?g'").contains("No") {
                BootloaderInfo = run("echo \"OpenCore - Version \" $(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}' | sed -e 's/ */./g' -e s'/^.//g' -e 's/.$//g' -e 's/ .//g' -e 's/. //g' | tr -d '\n') $( nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $1}' | sed -e 's/REL/(Release)/g' -e s'/N\\/A//g' -e 's/DEB/(Debug)/g' | tr -d '\n')")
            //} else {
                //BootloaderInfo = run("grep -A1 \"OpenCore Legacy Patcher\" /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist | tail -1 | sed -e 's?.?OCLP ?g' -e 's??, ?g'") + run("echo \"(OpenCore v\" $(nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version | awk '{print $2}' | awk -F'-' '{print $2}' | sed -e 's/ */./g' -e s'/^.//g' -e 's/.$//g' -e 's/ .//g' -e 's/. //g' | tr -d '\n'))")
            //}
```
I don't know if you can reproduce this on your system or if it is something related only to my system.

I also don't understand why the info obtained with the old code has `(Release)` and with the new code it doesn't, both blocks are almost identical, I only see one difference: `\"OpenCore - Version \"` is replaced by `\"OpenCore v\"`.

Anyway, if you don't reproduce the issue, sorry for the inconvenience, in that case I will try to find out what is happening.
Thank you!!!

Note: I hope I have explained myself well, English is not my native language.

**Comment by matxpa** [comment]
![Capture d’écran 2023-09-06 à 22 54 45](https://github.com/0xCUB3/About-This-Hack/assets/70573409/deb09502-ce96-41e5-952c-33785e161f1c)

**Comment by matxpa** [comment]
Hi @perez987 

 I will try to find out what is happening: github text editor is problematic, the code added to HCBootloader isn't the one I wrote, the difference is between Write and Preview editor behavior.  Some special chars disappear in the sed command content

Below is what you see in the post
![Capture d’écran 2023-09-07 à 11 47 30](https://github.com/0xCUB3/About-This-Hack/assets/70573409/52779acd-c621-4435-a992-90a8d8b174ed)

Below is what i wrote \<string\> and \<\/string\> disappeared so i have to protect with a backslash (\)
![Capture d’écran 2023-09-07 à 11 47 09](https://github.com/0xCUB3/About-This-Hack/assets/70573409/3163cee7-792e-42c8-a473-e93c61beb3a6)

Regards

**Comment by matxpa** [comment]
@perez987  Hi

And now the same (Sonoma 14.0 Dev beta 7) with Clover

![Capture d’écran 2023-09-07 à 16 36 44](https://github.com/0xCUB3/About-This-Hack/assets/70573409/9bd914c5-f87f-45d8-a878-2f645643efef)

Regards

**Comment by perez987** [comment]
@matxpa 
Well, there's probably something wrong with my system because I see that yours seems to work perfectly.

I assume you are running the app compiled from Xcode, right?
I have tested in Ventura 13.5.1 (Xcode 14.3.1) and in Sonoma beta 7 (Xcode 15 beta 8). Even deleting Xcode and its associated files and installing it again from scratch.

What happens to me is what I wrote in the first post. The app starts quickly and seems to work fine but I only get bootloader info if I comment out the code that checks if I have OCLP or Clover, leaving only the block that returns BootloaderInfo string with OpenCore info.

Thanks anyway.

**Comment by perez987** [comment]
@matxpa 
Out of curiosity: how do you get the ToolTip with extended info? I don't see it in the project anywhere. Thanks.

**Comment by matxpa** [comment]
@perez987 

Next step a fake NOT OCLP patched OS 
(file /System/Library/CoreServices/OpenCore-Legacy-Patcher.plist had been renamed so he can't exist)

![Capture d’écran 2023-09-07 à 17 03 17](https://github.com/0xCUB3/About-This-Hack/assets/70573409/5cdf60ea-6e9d-4046-a0af-a07018a3f48f)

you can't see OCLP detailed info with Bootloader (ToolTip)

Regards

**Comment by matxpa** [comment]
Tooltip it's so easy

A component added called ToolTips.swift with below content

//
//  ToolTips.swift
//  \<Project Name\>
//
//

import Foundation

let blPrefixtoolTip = HCBootloader.getBootloader()

No more thinks, you've just to declare a variable per display field cell on which you want see more info 
(here only one field has a ToolTip content) and you add a function in the component  ViewController.swift  (see below)

    func setToolTips(){
        blPrefix.toolTip = blPrefixtoolTip
    }
 you add all the fields (blPrefix here) you need and so on

I have opened a post in "Discussions" section few weeks ago

You ask me where you could find the way to extract OCLP info.
All the modifications made on "About-this-Hack" are only on a local repo (I don't want fork the project) it's experimental as I did on an other release (with bootargs, Kernel, SIP and Enrollment and many fields with ToolTip.

Regards

**Comment by 0xCUB3** [comment]
Should be fixed in the latest commit. Reopen if issue continues

**Comment by perez987** [comment]
@0xCUB3 
Thank you!!!

**Comment by perez987** [comment]
@0xCUB3 
Latest changes in bootloader info by @matxpa indeed have fixed this issue, all seems to be ok.

**Comment by 0xCUB3** [comment]
perfect! I might be releasing v1.0.0 soon
