### ISSUE TITLE
[Bug] macOS' Gatekeeper mechanism does not allow the app to run

### ISSUE THREAD

**Issue by pads1** [0xCUB3/About-This-Hack#5]
**Problem description**
The app could not run on my Mac. Error messages that appeared were "The application 'About This Hack' can't be opened.", and "'About This Hack' will damage your computer. You should move it to the Trash.". Moreover, I checked the app through Apparency, and I find out that Gatekeeper did not let the app run, but it was code-signed.

**Screenshot**
<img width="1212" alt="Screenshot 2022-08-20 at 9 51 19 AM" src="https://user-images.githubusercontent.com/23331269/185726444-44d46132-127e-45fc-8294-7c50d6d5d5c4.png">

**Specifications**
OS: Ventura 13.0 beta
Hardware: M1 MacBook Pro
App version: 0.5.0

**Comment by 0xCUB3** [comment]
@pads1 this isn't a bug. This is related to the fact that I don't have the paid Apple Developer license to sign the app, so apple often quarantines the app because of that. See solution in #6

**Comment by 0xCUB3** [comment]
@pads1 if that didn't work, please try the latest version: 0.6.0. All the issues should be resolved.
