### ISSUE TITLE
Can't open on High Sierra

### ISSUE THREAD

**Issue by baguswaber** [0xCUB3/About-This-Hack#52]
As per READ.ME, this app will work on Sierra and newer, but my Hackintosh can't run it and crash with following details below.
![Screen Shot 2023-09-16 at 05 23 20](https://github.com/0xCUB3/About-This-Hack/assets/20826856/75541bd7-d222-46bf-9c26-9014508c1000)
[AboutThisHackError.txt](https://github.com/0xCUB3/About-This-Hack/files/12629180/AboutThisHackError.txt)
[Send me 192.168.0.10.zip](https://github.com/0xCUB3/About-This-Hack/files/12629182/Send.me.192.168.0.10.zip)

**Comment by 0xCUB3** [comment]
can you try this latest build? I made a ton of changes since that release:
https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing

**Comment by baguswaber** [comment]
> can you try this latest build? I made a ton of changes since that release: https://drive.google.com/file/d/1Yq_M2M6xOI0SOXwh1JlagsrzdC6XGxk0/view?usp=sharing

Still crashing.
![Screen Shot 2023-09-16 at 05 46 24](https://github.com/0xCUB3/About-This-Hack/assets/20826856/cc4019a0-ccf0-4197-8771-230f8791d5b5)

**Comment by 0xCUB3** [comment]
interesting. You seem to have the same issue as #39, so I will close this one and move over there.
