### ISSUE TITLE
Update process fails and app crashes

### ISSUE THREAD

**Issue by perez987** [0xCUB3/About-This-Hack#54]
Good morning, the update process doesn't work, at least on my system.
Latest commit e13e1e8, builds without errors and runs fine.
To try the new update way (after the old Sparkle way), I change the app version (current 1.0.0) to a lower number, e.g. 0.9.9.
As expected, update fails from Xcode since the source app is not in the Applications folder but in DerivedData.
Moving the product to Applications, I get the Update Found dialog, clicking Update the old app is deleted from Applications but the new app never appears.
I think (not sure) that the error is in the zip phase, following the console when running update within Xcode:

```bash
Starting Update...
Starting Download...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     30      0 --:--:-- --:--:-- --:--:--    30
Warning: Failed to open the file 
Warning: /private/tmp/.ath/private/tmp/.ath/new_ath.zip: No such file or 
Warning: directory
curl: (23) Failure writing output to destination
curl: (3) URL rejected: No host part in the URL
Killing Old App...
zsh:1: unknown condition: -d
Unzipping Archive...
About_This_Hack/UpdateController.swift:54: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Message from debugger: killed
```

Really I don't know why it happens and if it'is only my problem. Did you try this? Does update work well for you?

Thank you.

**Comment by 0xCUB3** [comment]
This is because I don't have a newer release of the app lol. The update feature will not work until I actually make a release with it

**Comment by perez987** [comment]
@0xCUB3 
Thanks.
