### ISSUE TITLE
can not run in macOS 12.5.1

### ISSUE THREAD

**Issue by michelle0812** [0xCUB3/About-This-Hack#6]
os: macOS 12.5.1
About This Hack 0.5.0 Beta
can not run as following
<img width="645" alt="Screen Shot 2022-08-22 at 7 12 49 PM" src="https://user-images.githubusercontent.com/79300809/185908059-c7d5f61d-2728-42f3-b1d5-73134d64499b.png">
and  General Tab of Security & Privacy no show "Open Anyway"
<img width="780" alt="Screen Shot 2022-08-22 at 7 27 53 PM" src="https://user-images.githubusercontent.com/79300809/185910709-7259cf03-0e2e-46f1-b976-38d49c14c28c.png">
If I do sudo spctl --master-disable, the same issue happens again
<img width="780" alt="Screen Shot 2022-08-22 at 7 18 51 PM" src="https://user-images.githubusercontent.com/79300809/185910442-f17bcb7d-b585-4a0b-a9bd-8e122702eba0.png">

**Comment by 0xCUB3** [comment]
@michelle0812 this is because I am broke and don't have money to pay $99/year to sign the app. For some users, this will appear. To fix the issue, open your terminal and type `xattr -cr /Applications/About\ This\ Hack.app`

**Comment by 0xCUB3** [comment]
Please let me know if that resolves the issue

**Comment by michelle0812** [comment]
The same issue in my hackintosh
<img width="1249" alt="Screen Shot 2022-08-22 at 7 30 30 PM" src="https://user-images.githubusercontent.com/79300809/185911246-0ce9b642-030f-4a5a-8784-8eaec8d0d24b.png">

**Comment by 0xCUB3** [comment]
@michelle0812 in your Finder, go to About This Hack -> Show Contents -> Contents/MacOS and drag the executable there into the terminal.

**Comment by 0xCUB3** [comment]
@michelle0812 hold on, when I download 0.5.0 I'm getting this too. Try downloading 0.4.0 and then updating when it prompts you too. See if that works.

**Comment by 0xCUB3** [comment]
@michelle0812 if you haven't done the previous step yet, there shouldn't be a need. Try downloading the ZIP file from 0.5.0 again. I put in a new binary that should work.

**Comment by michelle0812** [comment]
Yes!!
Thank you.
New 0.5.0 OK..
I also tried 0.4.0 10mins ago but no ok.
Thank you Anyway.

**Comment by 0xCUB3** [comment]
@michelle0812 this is because I don't have the paid developer license. It seems that since my app got a ton of downloads without getting signed by a paid account, apple decided to quarantine it :( . It's never fun to be broke

**Comment by michelle0812** [comment]
got it! 
Thank you for your hard work

**Comment by 0xCUB3** [comment]
No problem. Closing as completed

**Comment by michelle0812** [comment]
Weird it can not run again in different hackintoshes which run macOS 12.5.1.
 I tried  with 0.5.0 and 0.4.0 but no works.

**Comment by michelle0812** [comment]
@0xCUB3 I use yesterday's hackintosh and can't run 0.5.0 today.

**Comment by 0xCUB3** [comment]
@michelle0812 like I said before, Apple is being mean to me because my app has a lot of downloads and I am not paying for the developer license. I contacted them about this and they said that the only way to resolve this issue is to pay them the $99/year and have the app properly signed. At this point, there is nothing that I can do to fix the issue. As a teenager, I have no way of paying the money, but since the app surpassed 1000 installations, Apple is being more and more restrictive.

**Comment by 0xCUB3** [comment]
@michelle0812 update: this release should fix everything. Let me know if it still doesn't work. Download it from here:
https://github.com/0xCUB3/About-This-Hack/releases/tag/0.6.0
