### ISSUE TITLE
Display Bug

### ISSUE THREAD

**Issue by frogg** [0xCUB3/About-This-Hack#60]
Very excited about this app, this is exactly what I need!

I couldn't make it work however:

- Downloaded latest version, moved to Applications directory
- Right click → Open
- App opens for 1s in the dock and then quits silently

No error message, security popup, etc is shown.

Any idea?

Konfiguration: M1 Pro MacBook Pro, macOS Sonoma Version 14.0 (23A344)

**Comment by MDNich** [comment]
Run from shell - open terminal and run the following:

```
$ ~/Downloads/About\ This\ Hack.app/Contents/MacOS/*
```

and show here what the output is

**Comment by MDNich** [comment]
Normal run looks like this:
```
$ ~/Downloads/About\ This\ Hack.app/Contents/MacOS/*
Directory created...
Files created...
14.0
OS Build Number:  (23A344) 
RAM Type: LPDDR5

RAM Speed: 
["Apple M2"]
1
Support View Initializing...
loaded
Initializing Main View...
TEST TEST /private/tmp/.ath/scr.txt
Number of Displays: 1
Has built-in display: true
Startup Disk Name Macintosh HD
Storage Type: true
Size: 994.7
Available: 448.2
%: 45.06
Storage Data: Macintosh HD (Internal Apple)
994.7 GB (448.2 GB Available - 45.06%)
Size: 994.7
Available: 448.2
%: 45.06
Storage Percent: 0.5494118829797929
TEST TEST /private/tmp/.ath/scr.txt
TEST TEST /private/tmp/.ath/scr.txt
RAM Type: LPDDR5

RAM Speed: 
["Apple M2"]
1
nvram: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version': (iokit/common) data was not found
OS Build Info: Darwin 23.0.0
SIP: Enabled 

Parse error: bad expression
    <stdin>:1

tail: -: No such file or directory
nvram: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version': (iokit/common) data was not found
Checking for Updates...
Checking for updates...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     6  100     6    0     0     21      0 --:--:-- --:--:-- --:--:--    21
```

**Comment by frogg** [comment]
Thanks, here you go:

```
Directory created...
Files created...
14.0
OS Build Number:  (23A344)
RAM Type: LPDDR5

RAM Speed:
["Apple M1 Pro"]
1
loaded
Support View Initializing...
Initializing Main View...
TEST TEST /private/tmp/.ath/scr.txt
Number of Displays: 2
Has built-in display: true
Startup Disk Name Macintosh HD
Storage Type: true
Size: 2.0
Available: 401.3
%: 20065.00
Storage Data: Macintosh HD (Internal Apple)
2.0 TB (401.3 GB Available - 20065.00%)
Size: 2.0
Available: 401.3
%: 20065.00
Storage Percent: -199.65
TEST TEST /private/tmp/.ath/scr.txt
TEST TEST /private/tmp/.ath/scr.txt
2 or 3 displays found
zsh:2: command not found: Color
[1]    62649 trace trap  /Applications/About\ This\ Hack.app/Contents/MacOS/*
```

**Comment by frogg** [comment]
(on a first glance I think it is confused by the 2TB, in your case the size is displayed in GB and thus the percentage is calculated in a much more reasonable way)

**Comment by MDNich** [comment]
I think it is rather the displays
Let me check the code there

**Comment by frogg** [comment]
You are right, unplugging from the display launches the app as expected.

Filed the other issue under #61

**Comment by MDNich** [comment]
Ok here is a question for you @frogg. Please upload zip and upload this folder (with the all displays attached): 
```
/tmp/.ath/
```

**Comment by MDNich** [comment]
@frogg if you could upload that folder 🙏 it would be awesome :)) until then we need someone else with a 3+ display setup.

**Comment by btxtiger** [comment]
@MDNich do you need the whole folder or just scr.txt ?
I have 3 displays, MacBook + 1x HDMI + 1x connected via DisplayLink DockingStation

**Comment by MDNich** [comment]
Thank you for scr.txt, could you send the whole folder too? That way I don't bug you later if I realize I need something else too :))

**Comment by matxpa** [comment]
@MDNich 

I suspect HCDisplay.swift with tail command (time delay problem with powerful processor)

This issue log content extraction
...
Parse error: bad expression
    <stdin>:1

tail: -: No such file or directory
...

I've a new PR,  

And a new PR on HCGPU.swift to avoid a time delay too

Regards

**Comment by matxpa** [comment]
@0xCUB3  @MDNich 

with the two last PR on Display and Graphics

![Capture d’écran 2023-10-11 à 13 22 14](https://github.com/0xCUB3/About-This-Hack/assets/70573409/235d33f6-4025-4164-9df8-3dbd50ccad63)

![Capture d’écran 2023-10-11 à 13 22 37](https://github.com/0xCUB3/About-This-Hack/assets/70573409/9a1e855b-e8f7-4278-a511-0c2c0ccf7d68)

I hope it'll work better with ARM Mn

Regards

**Comment by matxpa** [comment]
@MDNich 

to resolve the issue above
...
Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range
zsh: illegal hardware instruction
...

I modified ViewControllerDisplays.swift to 
1)change
...
                for i in [...  (each time I found for i in [...)
to 
                let indiceArray = [0,1]
                indiceArray.forEach { i in
...

and now the problem is on displayNames and displayRes arrays content

                displayNames has only one element (it's why the error message is : Index out of range)
                displayRes has tree elements (the third is empty)

...
switched
Initializing Display View...
Test
2 Displays Detected
HardwareCollector.displayNames = below
["Built-In Retina LCDColor LCD"]
HardwareCollector.displayRes = below
["3072 x 1920 Retina", "5120 x 2880 (5K/UHD+ - Ultra High Definition Plus)", ""]
Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range
zsh: illegal hardware instruction  
...

Regards

**Comment by matxpa** [comment]
@MDNich  @0xCUB3  @frogg 

![Capture d’écran 2023-10-11 à 20 44 53](https://github.com/0xCUB3/About-This-Hack/assets/70573409/bf60b09d-40c7-45a6-a3db-96271db0faef)

Normally the second display is a LG HDR 4K (isn't it ?)

**Comment by 0xCUB3** [comment]
it's not my computer so idk 🤷🏻

**Comment by matxpa** [comment]
Yes it's frogg's one, that's to say in the code the display name LG HDR 4K is lost

**Comment by matxpa** [comment]
![Capture d’écran 2023-10-11 à 22 09 00](https://github.com/0xCUB3/About-This-Hack/assets/70573409/124ace88-e431-4479-bcc9-302212db9a3d)

With second Display name

**Comment by 0xCUB3** [comment]
nice! Could you make a PR with the changes when they are ready? I am super busy this week so I don't have time to work on the app.

**Comment by matxpa** [comment]
@0xCUB3 

Yes I'll do that tomorrow, yet I'm tired.
It needs more tests and I'll have to clean some mad changes.

**Comment by matxpa** [comment]
@0xCUB3  @MDNich 

I've others cosmetic changes to do in ViewControllerDisplays.swift start() function

modify those two lines (was displayed in log constant "HardwareCollector.display..." not the two arrays content.
...
        print("HardwareCollector.displayNames = \"\(HardwareCollector.displayNames)\"")
        print("HardwareCollector.displayRes = \"\(HardwareCollector.displayRes)\"")
...
and add or restore that same debug code in "1 Display Detected" "2 Displays Detected" and "3 Displays Detected"

And I have a question about the value of Display on Overview tab : that content is the resolution of the display
wouldn't it be the name and the resolution ?
and with the two displays content (frogg's scr.txt) the MAIN display resolution isn't the one loaded in Display Text Field Cell , Main Display is LG HDR 4K with 5120 x 2880 (5K/UHD+ - Ultra High Definition Plus)  Resolution?

![Capture d’écran 2023-10-12 à 14 11 45](https://github.com/0xCUB3/About-This-Hack/assets/70573409/cc7f890f-ad79-402d-a00a-7d176c9f2fdb)

Regards

**Comment by matxpa** [comment]
@0xCUB3  @MDNich 

Identification of "Main Display" in HardwareCollector.swift

static func getDisplayMain() {
	var valueMainDisplay = ""
...
	if (numDispl > 1) {

	1) Display Name and Main one

	egrep "        |Main Display: " /tmp/testATH.txt | cut -c 9- | egrep "^[A-Za-z]|Main Display: " | while read Line
	do grep "${Line}" /tmp/testATH.txt | sed 's?^ *??g'
	done
	Color LCD:
	LG HDR 4K:
	Main Display: Yes

	2) Rank of Main Display in the list

	egrep "        |Main Display: " /tmp/testATH.txt | cut -c 9- | egrep "^[A-Za-z]|Main Display: " | while read Line
	do grep "${Line}" /tmp/testATH.txt | sed 's?^ *??g'
	done | grep -n "Main Display: "
	3:Main Display: Yes

	3) Rank (indice/index) of Main Display to identify the Display Name and/or Resolution in getDisplayNames()

	egrep "        |Main Display: " /tmp/testATH.txt | cut -c 9- | egrep "^[A-Za-z]|Main Display: " | while read Line
	do grep "${Line}" /tmp/testATH.txt | sed 's?^ *??g'
	done | grep -n "Main Display: " | awk -F':' '{print $1-1}'
	2 (in rankMain var)
}

	4)  In ViewControllerDisplays.swift (index calaculated in HardwareCollector.swift = 2-1 (first Array Index=0 not 1)
	let indexMainValue = Int(HardwareCollector.rankMain-1)
		if (indexMainValue <= (HardwareCollector.displayNames.count-1) ) {
			valueMainDisplay = HardwareCollector.displayNames[indexMainValue]
		}
		if (indexMainValue <= (HardwareCollector.displayRes.count-1) ) {
			valueMainDisplay += HardwareCollector.displayRes[indexMainValue]
		}
	}
}

5) In HardwareCollector.swift

	    static var MainDisplay: String = ""
... in     static func getAllData() {
        displayMain = getDisplayMain()
        
6) In ViewController.swift
...     func start() {
	        // Display
        	//display.stringValue = HCDisplay.getDisp()
         	display.stringValue = HCDisplay.getDisplayMain()
         	
         	
And in conclusion the content of HCDisplay.getDisp() could be replace with the content above or to add the func getDisplayMain()

It's just a draft not usable as this and Display in Overview tab could be LG HDR 4K 5120 x 2880 (5K/UHD+ - Ultra High Definition Plus)

Regards

**Comment by matxpa** [comment]
@0xCUB3  @MDNich  @frogg 

ATH app with issue 60 fixed (Built with Xcode 14.2) without Main Display Identification
https://drive.google.com/file/d/1V6TGt6UpoybhsgZUlRGLsN7FSy6DsNpb/view?usp=sharing

If someone has three connected displays ...

**Comment by MDNich** [comment]
Je le teste maintenant @matxpa . Merci

**Comment by MDNich** [comment]
Juste de curiosité, quelle signature avez-vous mis sur la app ? Signé pour exécution locale, ou avec un AppleID ?

**Comment by matxpa** [comment]
HI

Sign To Run Locally (with Auto manage signing OFF)
(otherwise Xcode 15.0 error)

L'appli ne se lance pas ?

Sinon mon Repo (main branch is up to date) pour compilation en modifiant le mode d'exécution (
Je peux la (re)compiler sous Xcode 15.0 (mais se sera toujours en Locally, sinon j'ai une erreur)
Je pense revenir sous Xcode 14.x, j'ai trop de crash avec Xcode 15 et le Debug ne fonctionne pas (Xcode 15.0 issue)

![Capture d’écran 2023-10-12 à 17 27 45](https://github.com/0xCUB3/About-This-Hack/assets/70573409/7a35f4fc-f2e7-4121-b080-9757766a28cf)


Salutations

**Comment by MDNich** [comment]
Non non ça marche, c'est juste je voulais bien confirmer le comportement de macOS quand la app n'est pas signé comme dans ce cas. Merci bcp

Mois j'utilise Xcode 15.0 pour l'instant - ça va:)

**Comment by matxpa** [comment]
I hope frogg will be satisfied

**Comment by matxpa** [comment]
@0xCUB3  @MDNich  @frogg 

Prototype of Display (Main display)

![Capture d’écran 2023-10-12 à 20 42 59](https://github.com/0xCUB3/About-This-Hack/assets/70573409/f2393063-edda-488e-bf74-61b569cb92a2)

![Capture d’écran 2023-10-12 à 20 46 27](https://github.com/0xCUB3/About-This-Hack/assets/70573409/3e87e9a1-7af8-495f-a1e7-d930905d6b95)

And with only one Display

![Capture d’écran 2023-10-12 à 20 49 52](https://github.com/0xCUB3/About-This-Hack/assets/70573409/7dc6b11a-0d41-49c3-b7d3-557162a1c378)

![Capture d’écran 2023-10-12 à 20 51 01](https://github.com/0xCUB3/About-This-Hack/assets/70573409/a13f5f90-11b5-4efc-9684-899ae39a8161)

Regards

**Comment by matxpa** [comment]
@0xCUB3  @MDNich  @frogg 

ATH app with Main Display Identification (Built with Xcode 15.0) 
https://drive.google.com/file/d/1LCqRZUqzGzY72pSg8WtbklfysDAQx_i6/view?usp=sharing

Regards

**Comment by matxpa** [comment]
@0xCUB3  @MDNich 

With more than one Displays, in Overview Tab in Display content do you want to see resolution of Main Display or resolution of first Display even if it's not the Main one ?

WIth 2 Displays (frogg's Displays)

![Capture d’écran 2023-10-13 à 16 02 35](https://github.com/0xCUB3/About-This-Hack/assets/70573409/8a917b6e-e7fa-45f2-9121-5e284826eb87)

![Capture d’écran 2023-10-13 à 16 02 53](https://github.com/0xCUB3/About-This-Hack/assets/70573409/7177aa67-0214-4d8f-8023-37abfe631a95)

The necessary changes could be (not pushed) (don't try to copy the code below which isn't WYSIWYG)

1) In ViewController.swift
...
 //       _ = HCDisplay.getDisp()
        _ = HCDisplay.getDispMain()
...
        // Display
//        display.stringValue = HCDisplay.getDisp()
        display.stringValue = HCDisplay.getDispMain()
...

2) In HardwareCollectors/HCDisplay.swift, add function getDispMain (and keep getDisp to revert to present code)
...
    static func getDispMain() -> String {
        let resolutionList: [String] = run("grep \"Resolution\" " + initGlobVar.scrFilePath  + " | cut -c 23-").components(separatedBy: "\n")
        print("resolutionList = " + "\(resolutionList)")
        let dispMainList: [String] = run("egrep \"        |Main Display: \" " + initGlobVar.scrFilePath + " | cut -c 9- | egrep \"^[A-Za-z]|Main Display: \" | sed 's/ *Main Display: /Main /'").components(separatedBy: "\n")
        print("dispMainList = " + "\(dispMainList)")
        let indexMain:Int = (dispMainList.firstIndex(of: "Main Yes") ?? 0) - 1
        print("indexMain = " + "\(indexMain)")
        var valueMainDisplay: String = ""
        if (indexMain <= (dispMainList.count-1) ) && (indexMain <= (resolutionList.count-1) ) {
            valueMainDisplay = "\(resolutionList[indexMain])"
        }
        return ("\(valueMainDisplay)")
    }
...

Regards
