### ISSUE TITLE
Immediate crash after opening

### ISSUE THREAD

**Issue by pw951590** [0xCUB3/About-This-Hack#63]
Use latest 1.0.0 version, copied to application folder, started and immediately crashed:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               About This Hack [79723]
Path:                  /Applications/About This Hack.app/Contents/MacOS/About This Hack
Identifier:            app.netlify.0xCUBE.About-This-Hack
Version:               1.0.0 (1337)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-10-10 11:39:48.5104 +0200
OS Version:            macOS 14.0 (23A344)
Report Version:        12
Anonymous UUID:        A9D81DBF-F5DE-878D-820F-AA12CD1E1DF1

Time Awake Since Boot: 520000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000102d5c404

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [79723]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   About This Hack               	       0x102d5c404 0x102d4c000 + 66564
1   About This Hack               	       0x102d5c9ac 0x102d4c000 + 68012
2   About This Hack               	       0x102d4ed14 0x102d4c000 + 11540
3   About This Hack               	       0x102d4ec0c 0x102d4c000 + 11276
4   About This Hack               	       0x102d4ec40 0x102d4c000 + 11328
5   AppKit                        	       0x1915270ac -[NSViewController _sendViewDidAppear] + 56
6   AppKit                        	       0x191eaea08 -[NSView _windowDidOrderOnScreen] + 56
7   AppKit                        	       0x191eaea74 -[NSView _windowDidOrderOnScreen] + 164
8   AppKit                        	       0x191eaea74 -[NSView _windowDidOrderOnScreen] + 164
9   AppKit                        	       0x191eaea74 -[NSView _windowDidOrderOnScreen] + 164
10  AppKit                        	       0x191ec3420 -[NSWindow _reallyDoOrderWindowAboveOrBelow:] + 1600
11  AppKit                        	       0x191ec3d94 -[NSWindow _reallyDoOrderWindow:] + 64
12  AppKit                        	       0x191ec3ff4 -[NSWindow _doOrderWindow:] + 264
13  AppKit                        	       0x191517c84 -[NSWindow makeKeyAndOrderFront:] + 40
14  QuickLookUI                   	       0x1fc5cc640 -[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:] + 184
15  AppKit                        	       0x1915f0cf0 -[NSWindowController showWindow:] + 496
16  AppKit                        	       0x1913ef634 NSApplicationMain + 668
17  About This Hack               	       0x102d4ffb0 0x102d4c000 + 16304
18  dyld                          	       0x18d7f5058 start + 2224

Thread 1:
0   libsystem_pthread.dylib       	       0x18db69e28 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18db69e28 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x18db69e28 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x18db69e28 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x000060000369ff30   x1: 0x80000004ffffffff   x2: 0x0000000000000000   x3: 0x00000001e69d7f78
    x4: 0x0000000000000002   x5: 0x0000000000003f30   x6: 0xec00000053504920   x7: 0x00000000000d0007
    x8: 0x0000000000000002   x9: 0xffffffffffffffff  x10: 0x80000002ffffffff  x11: 0x00000000000009f6
   x12: 0x0000600003ac67d8  x13: 0x00000000001ff800  x14: 0x00000000000007fb  x15: 0x00000000bd005952
   x16: 0x000000019d781104  x17: 0x00000000000091a2  x18: 0x0000000000000000  x19: 0x693732204e454d4f
   x20: 0x000000016d0b2ec0  x21: 0x000060000369ff30  x22: 0xed00000a53504920  x23: 0x0000000000000001
   x24: 0xec00000053504920  x25: 0xd00000000000001b  x26: 0x000000000000000a  x27: 0x0000600002da3f00
   x28: 0x0000600002da3d40   fp: 0x000000016d0b2f20   lr: 0x0000000102d5c390
    sp: 0x000000016d0b2e90   pc: 0x0000000102d5c404 cpsr: 0x80001000
   far: 0x000000015501c620  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x102fa4000 -        0x102faffff libobjc-trampolines.dylib (*) <562f95b3-8118-3d61-a13f-34e819dd863d> /usr/lib/libobjc-trampolines.dylib
       0x102d4c000 -        0x102d67fff app.netlify.0xCUBE.About-This-Hack (1.0.0) <e9701af2-0207-3b70-8848-392377afa809> /Applications/About This Hack.app/Contents/MacOS/About This Hack
       0x1913eb000 -        0x1926fbfff com.apple.AppKit (6.9) <a4e78dd1-6b6e-3f57-924a-4a6a2e679789> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x1fc536000 -        0x1fc669fff com.apple.QuickLookUIFramework (5.0) <1740310d-9358-386b-9373-4bfce0265b10> /System/Library/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
       0x18d7ef000 -        0x18d882873 dyld (*) <ffd8ab66-c9ab-31df-ab80-3a3dff367ddd> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x19d399000 -        0x19d8d8fff libswiftCore.dylib (*) <9d952ae1-e049-3444-96e3-0a5756c0b89d> /usr/lib/swift/libswiftCore.dylib
       0x18db68000 -        0x18db74ff3 libsystem_pthread.dylib (*) <e4debb6e-421d-33d0-9e17-77ae0e0fe4dc> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)
Writable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG image                            64K        1 
ColorSync                          528K       24 
CoreGraphics                        32K        2 
CoreUI image data                  544K        6 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                             1.5G       48 
MALLOC guard page                  192K       12 
STACK GUARD                       56.1M        5 
Stack                             10.1M        5 
VM_ALLOCATE                         48K        3 
__AUTH                            1654K      321 
__AUTH_CONST                      27.3M      524 
__CTF                               824        1 
__DATA                            12.4M      510 
__DATA_CONST                      26.6M      532 
__DATA_DIRTY                      1698K      191 
__FONT_DATA                        2352        1 
__LINKEDIT                       886.5M        3 
__OBJC_RO                         70.6M        1 
__OBJC_RW                         2153K        1 
__TEXT                           584.4M      551 
dyld private memory                272K        2 
mapped file                      194.3M       22 
shared memory                      848K       13 
===========                     =======  ======= 
TOTAL                              3.3G     2783 

-----------
Full Report
-----------

{"app_name":"About This Hack","timestamp":"2023-10-10 11:39:49.00 +0200","app_version":"1.0.0","slice_uuid":"e9701af2-0207-3b70-8848-392377afa809","build_version":"1337","platform":1,"bundleID":"app.netlify.0xCUBE.About-This-Hack","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.0 (23A344)","roots_installed":0,"name":"About This Hack","incident_id":"F38F3A91-06A0-4606-8E6C-D1F1B822A5FA"}
{
  "uptime" : 520000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac13,1",
  "coalitionID" : 257086,
  "osVersion" : {
    "train" : "macOS 14.0",
    "build" : "23A344",
    "releaseType" : "User"
  },
  "captureTime" : "2023-10-10 11:39:48.5104 +0200",
  "codeSigningMonitor" : 1,
  "incident" : "F38F3A91-06A0-4606-8E6C-D1F1B822A5FA",
  "pid" : 79723,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-10-10 11:39:46.5398 +0200",
  "procStartAbsTime" : 12638662466031,
  "procExitAbsTime" : 12638709279344,
  "procName" : "About This Hack",
  "procPath" : "\/Applications\/About This Hack.app\/Contents\/MacOS\/About This Hack",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.0","CFBundleVersion":"1337","CFBundleIdentifier":"app.netlify.0xCUBE.About-This-Hack"},
  "storeInfo" : {"deviceIdentifierForVendor":"29BD9F63-2E7C-561E-9917-354C4F651C60","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "app.netlify.0xCUBE.About-This-Hack",
  "crashReporterKey" : "A9D81DBF-F5DE-878D-820F-AA12CD1E1DF1",
  "codeSigningID" : "app.netlify.0xCUBE.About-This-Hack",
  "codeSigningTeamID" : "T474C55Q79",
  "codeSigningFlags" : 1644245777,
  "codeSigningValidationCategory" : 3,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"9QMAqi3\/\/xfgXwkQHyAD1WHYABAfIAPVLBIAlGH\/\/xcgACDUIAAg1A==","atPC":"IAAg1P9DAtH8bwOp+mcEqfhfBan2Vwap9E8Hqf17CKn9AwKRiAAA8A=="},
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x0000000102d5c404","rawCodes":[1,4342531076],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":79723},
  "os_fault" : {"process":"About This Hack"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":16363425,"threadState":{"x":[{"value":105553173544752},{"value":9223372058329612287},{"value":0},{"value":8164048760,"symbolLocation":0,"symbol":"type metadata for String"},{"value":2},{"value":16176},{"value":17005592194348763424},{"value":851975},{"value":2},{"value":18446744073709551615},{"value":9223372049739677695},{"value":2550},{"value":105553177896920},{"value":2095104},{"value":2043},{"value":3170916690},{"value":6936858884,"symbolLocation":0,"symbol":"swift_bridgeObjectRelease"},{"value":37282},{"value":0},{"value":7581583612035026255},{"value":6124416704},{"value":105553173544752},{"value":17077649831336364320},{"value":1},{"value":17005592194348763424},{"value":14987979559889010715},{"value":10},{"value":105553164123904},{"value":105553164123456}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4342530960},"cpsr":{"value":2147487744},"fp":{"value":6124416800},"sp":{"value":6124416656},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4342531076,"matchesCrashFrame":1},"far":{"value":5721146912}},"queue":"com.apple.main-thread","frames":[{"imageOffset":66564,"imageIndex":1},{"imageOffset":68012,"imageIndex":1},{"imageOffset":11540,"imageIndex":1},{"imageOffset":11276,"imageIndex":1},{"imageOffset":11328,"imageIndex":1},{"imageOffset":1294508,"symbol":"-[NSViewController _sendViewDidAppear]","symbolLocation":56,"imageIndex":2},{"imageOffset":11287048,"symbol":"-[NSView _windowDidOrderOnScreen]","symbolLocation":56,"imageIndex":2},{"imageOffset":11287156,"symbol":"-[NSView _windowDidOrderOnScreen]","symbolLocation":164,"imageIndex":2},{"imageOffset":11287156,"symbol":"-[NSView _windowDidOrderOnScreen]","symbolLocation":164,"imageIndex":2},{"imageOffset":11287156,"symbol":"-[NSView _windowDidOrderOnScreen]","symbolLocation":164,"imageIndex":2},{"imageOffset":11371552,"symbol":"-[NSWindow _reallyDoOrderWindowAboveOrBelow:]","symbolLocation":1600,"imageIndex":2},{"imageOffset":11373972,"symbol":"-[NSWindow _reallyDoOrderWindow:]","symbolLocation":64,"imageIndex":2},{"imageOffset":11374580,"symbol":"-[NSWindow _doOrderWindow:]","symbolLocation":264,"imageIndex":2},{"imageOffset":1232004,"symbol":"-[NSWindow makeKeyAndOrderFront:]","symbolLocation":40,"imageIndex":2},{"imageOffset":616000,"symbol":"-[QLSeamlessDocumentOpener showWindow:contentFrame:withBlock:]","symbolLocation":184,"imageIndex":3},{"imageOffset":2120944,"symbol":"-[NSWindowController showWindow:]","symbolLocation":496,"imageIndex":2},{"imageOffset":17972,"symbol":"NSApplicationMain","symbolLocation":668,"imageIndex":2},{"imageOffset":16304,"imageIndex":1},{"imageOffset":24664,"symbol":"start","symbolLocation":2224,"imageIndex":4}]},{"id":16363432,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6124974080},{"value":4611},{"value":6124437504},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6124974080},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6672522792},"far":{"value":5772460032}}},{"id":16363433,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6125547520},{"value":9987},{"value":6125010944},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6125547520},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6672522792},"far":{"value":4306833528}}},{"id":16363434,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6126120960},{"value":20743},{"value":6125584384},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6126120960},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6672522792},"far":{"value":4698701824}}},{"id":16363436,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}],"threadState":{"x":[{"value":6126694400},{"value":18947},{"value":6126157824},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6126694400},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6672522792},"far":{"value":105553146511360}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4344922112,
    "size" : 49152,
    "uuid" : "562f95b3-8118-3d61-a13f-34e819dd863d",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4342464512,
    "CFBundleShortVersionString" : "1.0.0",
    "CFBundleIdentifier" : "app.netlify.0xCUBE.About-This-Hack",
    "size" : 114688,
    "uuid" : "e9701af2-0207-3b70-8848-392377afa809",
    "path" : "\/Applications\/About This Hack.app\/Contents\/MacOS\/About This Hack",
    "name" : "About This Hack",
    "CFBundleVersion" : "1337"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6731771904,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 19992576,
    "uuid" : "a4e78dd1-6b6e-3f57-924a-4a6a2e679789",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8528289792,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.QuickLookUIFramework",
    "size" : 1261568,
    "uuid" : "1740310d-9358-386b-9373-4bfce0265b10",
    "path" : "\/System\/Library\/Frameworks\/QuickLookUI.framework\/Versions\/A\/QuickLookUI",
    "name" : "QuickLookUI",
    "CFBundleVersion" : "986"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6668873728,
    "size" : 604276,
    "uuid" : "ffd8ab66-c9ab-31df-ab80-3a3dff367ddd",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6932762624,
    "size" : 5505024,
    "uuid" : "9d952ae1-e049-3444-96e3-0a5756c0b89d",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6672515072,
    "size" : 53236,
    "uuid" : "e4debb6e-421d-33d0-9e17-77ae0e0fe4dc",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6668124160,
  "size" : 4012523520,
  "uuid" : "7906534c-5d2b-3ba8-b9c6-93a5cf1b7b50"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.4G resident=0K(0%) swapped_out_or_unallocated=1.4G(100%)\nWritable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG image                            64K        1 \nColorSync                          528K       24 \nCoreGraphics                        32K        2 \nCoreUI image data                  544K        6 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                             1.5G       48 \nMALLOC guard page                  192K       12 \nSTACK GUARD                       56.1M        5 \nStack                             10.1M        5 \nVM_ALLOCATE                         48K        3 \n__AUTH                            1654K      321 \n__AUTH_CONST                      27.3M      524 \n__CTF                               824        1 \n__DATA                            12.4M      510 \n__DATA_CONST                      26.6M      532 \n__DATA_DIRTY                      1698K      191 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       886.5M        3 \n__OBJC_RO                         70.6M        1 \n__OBJC_RW                         2153K        1 \n__TEXT                           584.4M      551 \ndyld private memory                272K        2 \nmapped file                      194.3M       22 \nshared memory                      848K       13 \n===========                     =======  ======= \nTOTAL                              3.3G     2783 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "594d5dcd20d82ac53e2010dcb2573916b78fb6fd",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "632e379301482c74ed76386c",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL" : "64e51357c83b9a3d50649dae",
        "SIRI_UNDERSTANDING_MORPHUN" : "64e5135c4e666d798a8ffc38",
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "6513719a8d79034dd899e35d"
      },
      "deploymentId" : 240000438
    },
    {
      "rolloutId" : "64b21a7351cbb02ce3442e4e",
      "factorPackIds" : {
        "REMINDERS_GROCERY" : "64d6bf89aa6c2933834d3f9d"
      },
      "deploymentId" : 240000018
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    },
    {
      "treatmentId" : "c33fe063-bfef-44d9-a26d-5911bece3957",
      "experimentId" : "645c25d467209f0eff81b889",
      "deploymentId" : 400000010
    }
  ]
}
}

Model: Mac13,1, BootROM 10151.1.1, proc 10:8:2 processors, 32 GB, SMC 
Graphics: Apple M1 Max, Apple M1 Max, Built-In
Display: OMEN 27i IPS, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), Main, MirrorOff, Online
Display: S2719DGF, 2560 x 1440 (QHD/WQHD - Wide Quad High Definition), MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Aug  8 2023 04:27:20 version 20.10.1062.3.8.7.162 FWID 01-c101870a
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Network Service: iPad, Ethernet, en18
PCI Card: pci1b21,622, AHCI Controller, Thunderbolt@5,0,0
PCI Card: pci1b73,1100, USB eXtensible Host Controller, Thunderbolt@4,0,0
PCI Card: Aquantia AQC107, Ethernet Controller, Thunderbolt@3,0,0
PCI Card: pci144d,a80a, NVM Express Controller, Thunderbolt@6,0,0
PCI Card: pci144d,a80a, NVM Express Controller, Thunderbolt@5,0,0
PCI Card: pci144d,a80a, NVM Express Controller, Thunderbolt@3,0,0
PCI Card: pci144d,a80a, NVM Express Controller, Thunderbolt@4,0,0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: Stream Deck Plus
USB Device: USB2.0 Hub
USB Device: Sound BlasterX G1
USB Device: iPad
USB Device: USB2.0 Hub
USB Device: Magic Keyboard with Touch ID and Numeric Keypad
USB Device: USB MICROPHONE
USB Device: USB31Bus
USB Device: USB2 Hub
USB Device: Apple Watch Magnetic Charging Cable
USB Device: USB3 Gen2 Hub
USB Device: Logitech BRIO
USB Device: USB30Bus
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Device: Express 4M2, Other World Computing, 1, 33.1
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Device: Thunderbolt 3 Pro Dock, Other World Computing, 1, 41.1
Thunderbolt Bus: Mac Studio, Apple Inc.
Thunderbolt Bus: Mac Studio, Apple Inc.

**Comment by MDNich** [comment]
I think this is the same as #60 , closing
