### ISSUE TITLE
Multiple GPUs

### ISSUE THREAD

**Issue by renatocanton** [0xCUB3/About-This-Hack#7]
It would be nice to see multiple GPUs, not just one like today
<img width="692" alt="Screenshot 2022-08-25 at 20 54 42" src="https://user-images.githubusercontent.com/69393515/186765397-e5d64bf5-74e9-4b85-8898-55a025be90b6.png">
.

**Comment by 0xCUB3** [comment]
Hello,
Due to the constraints of Swift storyboards, I haven’t been able to come up with a solution for two GPUs yet. I’m working on it but haven’t found a way yet. If you have any ideas that you want to contribute, feel free to make a PR with any changes. Thanks!

**Comment by nocontent06** [comment]
Pre added first version. Updating later. Currently available in [0.9.0+](https://github.com/0xCUB3/About-This-Hack/releases/tag/0.9.0)
