### ISSUE TITLE
App update function not working

### ISSUE THREAD

**Issue by 5T33Z0** [0xCUB3/About-This-Hack#70]
Seems like the App Update function does not work:

![Bildschirmfoto 2023-10-19 um 11 11 05](https://github.com/0xCUB3/About-This-Hack/assets/76865553/8764c2f3-9447-4118-affb-3e96e858c3d4)

macOS: 14.1 (23B73)

Greetings

**Comment by 0xCUB3** [comment]
This is because 0.9.1 still uses the old Sparkle updater, which hasn't been fed the new version because I switched to my own updater.

Please update manually.
