### ISSUE TITLE
No displays info - v1.0.0

### ISSUE THREAD

**Issue by Matgen84** [0xCUB3/About-This-Hack#72]
Hi

The version v1.0.0 don't detect my video card (Nvidia GT640) and of course  Iiyama monitor connected by HDMI.

macOS: 12.7 Monterey
SMBIOS: macpro6,1
Bootloader: Clover r5151

Thanks

**Comment by 0xCUB3** [comment]
is your GPU currently enabled? Does it show up in the regular About This Mac? If it doesn't, there is no way for it to show up in About This Hack.

**Comment by Matgen84** [comment]
my GPU currently show up in the official About This Mac.

**Comment by 0xCUB3** [comment]
if you know how, could you drag the app's binary into a terminal window, run it there, and send the output? Thanks

**Comment by matxpa** [comment]
@Matgen84 

Hi
Look at the end of #71 and #60 closed issues
Regards

**Comment by Matgen84** [comment]
@0xCUB3 

The output is there

[Résultat de Terminal.txt](https://github.com/0xCUB3/About-This-Hack/files/13167979/Resultat.de.Terminal.txt)
re.

**Comment by Matgen84** [comment]
@matxpa 

Hi
I look the closed issues. But I don't understand.

In my case, ATM doesn't display the monitor and graphics card. I've applied root-patches for my Nvidia and iGPU. Maybe this is causing a problem!

Thanks

**Comment by Matgen84** [comment]
@matxpa 

Hi

The file is there

Regards
[TMP ath files.zip](https://github.com/0xCUB3/About-This-Hack/files/13197207/TMP.ath.files.zip)

**Comment by Matgen84** [comment]
@0xCUB3 

The screenshot is there

Regards
![Capture d’écran 2023-10-29 à 05 57 05](https://github.com/0xCUB3/About-This-Hack/assets/5956729/e6da8027-01b5-415b-bc34-a1e5c1658c76)

**Comment by matxpa** [comment]
@Matgen84 @0xCUB3 @MDNich 

Hi
Matgen84, normally you'd like to see that
just consider "Graphics" content on Overview (other contents come from my Laptop)
"/tmp/.ath/scr.txt" used is a link on the file (sct.txt) you provided.

![Capture d’écran 2023-10-29 à 10 15 56](https://github.com/0xCUB3/About-This-Hack/assets/70573409/ec2f045a-fa5f-4d93-8e73-4c940eb87525)

![Capture d’écran 2023-10-29 à 10 16 16](https://github.com/0xCUB3/About-This-Hack/assets/70573409/ee866b4c-130c-4430-acf7-bdae6945117c)

You can try this ATH (a Xcode 15.1 build with actual 0xCUB3 repo content (with many fixes))
https://drive.google.com/file/d/1vfwjawuaJSrjRhaCJja96oz5-VuhUSRz/view?usp=drive_link

Regards

**Comment by Matgen84** [comment]
@matxpa @0xCUB3 

Unfortunalely, same issue with About my Hack (XCode 15.1). No problem with Slice's fork version 1.0.3: this ATH show up Display, graphic and acceleration.

Regards

**Comment by matxpa** [comment]
@Matgen84 @0xCUB3 
Hi
Could you try this modified "About this Hack.app" 
https://drive.google.com/file/d/1vfwjawuaJSrjRhaCJja96oz5-VuhUSRz/view?usp=drive_link

result should be as follows (on my HW with your DataFiles)

![Capture d’écran 2023-10-31 à 11 01 15](https://github.com/0xCUB3/About-This-Hack/assets/70573409/09bf9570-35a9-46fe-83a9-b41d783793b8)

![Capture d’écran 2023-10-31 à 11 01 39](https://github.com/0xCUB3/About-This-Hack/assets/70573409/3085e3df-2150-4fd0-a8b4-81bff6d4d7cb)

![Capture d’écran 2023-10-31 à 11 01 49](https://github.com/0xCUB3/About-This-Hack/assets/70573409/6bc29366-9b42-41f2-8397-999c672aebaf)


Regards

**Comment by yanisalbert** [comment]
Hi, i've the same issues 

V1.0.0
![Capture d’écran 2023-11-01 à 07 57 56](https://github.com/0xCUB3/About-This-Hack/assets/87071207/e042ecaa-d0c3-41b3-b3e1-8f56e99c3efe)
![Capture d’écran 2023-11-01 à 07 58 02](https://github.com/0xCUB3/About-This-Hack/assets/87071207/8a6ca670-1f85-4fa8-ba06-77f7b80e3fde)

With the V0.5.0
![Capture d’écran 2023-11-01 à 07 57 27](https://github.com/0xCUB3/About-This-Hack/assets/87071207/a2ccc00a-93fc-4e4b-a671-a9cf4e3dceec)
![Capture d’écran 2023-11-01 à 07 57 32](https://github.com/0xCUB3/About-This-Hack/assets/87071207/01f3026b-eb9d-4ed8-bc1f-de0c722e7d02)

Thanks

**Comment by matxpa** [comment]
@yanisalbert 

Hi
Is this behavior systematic, it works on many other Hard.
Could you send us your DataFiles : Launch ATH, hide critical content inside /tmp/.ath/*.txt DataFiles and zip /tmp/.ath rep.
Thanks  
Regards

**Comment by yanisalbert** [comment]
@matxpa  here is the file. Regards

[ath.zip](https://github.com/0xCUB3/About-This-Hack/files/13225109/ath.zip)

**Comment by matxpa** [comment]
Thanks

**Comment by Matgen84** [comment]
@matxpa @0xCUB3 

With the version upload yesterday, it's worse ! And  .ATH directory doesn't create in /private/tmp ?

![Capture d’écran 2023-11-01 à 13 50 38](https://github.com/0xCUB3/About-This-Hack/assets/5956729/216f9a8d-376e-4f4c-8b49-74aa52cf4b26)

**Comment by matxpa** [comment]
@Matgen84  @0xCUB3 @yanisalbert @nocontent06 @perez987 

Hi
I apologize.

Previous versions I push on Google Drive are perhaps TEST versions, the one I push 2 hours ago is a TEST version, so get rid of all of them.
TEST version coz' DataFiles contents of "/tmp/.ath/*.txt" coming from issues N39, N72, N78 are all different, specially "scr.txt" used to fill Displays and Graphics text cells.
TESTS are managed by the single component CreateDataFiles.swift, creating symbolic links of sent DataFiles in /tmp/.ath.

and you can try this last one

https://drive.google.com/file/d/1vfwjawuaJSrjRhaCJja96oz5-VuhUSRz/view?usp=drive_link

Regards

**Comment by matxpa** [comment]
@Matgen84 @0xCUB3 @yanisalbert @nocontent06 @kristibektashi @perez987

Hi yanisalbert
The content of the DataFiles you sent is anther scenario (scr.txt), a case never seen and ATH need modification(s).

![Capture d’écran 2023-11-01 à 15 09 37](https://github.com/0xCUB3/About-This-Hack/assets/70573409/5173ddd0-6a02-4e8e-a0b1-bc93c1974f8f)

On Displays Tab there's no Display name (coz' there's no string "Display Type" in content of scr.txt).

      Displays:
        Mi Monitor:
          Resolution: 3440 x 1440 (UWQHD - Ultra-Wide Quad HD)
          UI Looks like: 3440 x 1440 @ 144.00Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Connection Type: Thunderbolt/DisplayPort
        Beyond TV:
          Resolution: 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)
          UI Looks like: 3840 x 2160 @ 60.00Hz
          Framebuffer Depth: 30-Bit Color (ARGB2101010)
          Mirror: Off
          Online: Yes
          Rotation: Supported
          Television: Yes

And with another (new) modification

![Capture d’écran 2023-11-01 à 16 01 05](https://github.com/0xCUB3/About-This-Hack/assets/70573409/83831176-5abf-4952-8266-ea79222e246e)

And the last new version (tested with different DataFiles content for issues 39, 72(2) and 78 available with link
https://drive.google.com/file/d/1vfwjawuaJSrjRhaCJja96oz5-VuhUSRz/view?usp=sharing

And if you know somebody with other(s) Hard config you can send us their specific Datas. Thanks
And now I'll test it on High Sierra, kristibektashi is waiting for. 

Regards

**Comment by yanisalbert** [comment]
Ok

**Comment by Matgen84** [comment]
@matxpa @0xCUB3 

Despite src.txt, the last new version don't showing up Display and Graphics, also Metal:
`
    NVIDIA GeForce GT 640:

      Chipset Model: NVIDIA GeForce GT 640
      Type: GPU
      Bus: PCIe
      Slot: PCI Slot 0
      PCIe Lane Width: x16
      VRAM (Total): 2 GB
      Vendor: NVIDIA (0x10de)
      Device ID: 0x0fc1
      Revision ID: 0x00a2
      ROM Revision: VBIOS 80.07.55.00.0f
      Metal Family: Supported, Metal GPUFamily macOS 1
      Displays:
        PLX2483H:
          Resolution: 1920 x 1080 (1080p FHD - Full High Definition)
          UI Looks like: 1920 x 1080 @ 60.00Hz
          Framebuffer Depth: 24-Bit Color (ARGB8888)
          Display Serial Number: 1128050203504
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Rotation: Supported`

Rembember, I use Clover as Bootloader.  

Regards

[ATH-Binary.txt](https://github.com/0xCUB3/About-This-Hack/files/13236241/ATH-Binary.txt)

**Comment by 0xCUB3** [comment]
Fixed with #80
