### ISSUE TITLE
Display Preferences button does nothing

### ISSUE THREAD

**Issue by perez987** [0xCUB3/About-This-Hack#73]
Good morning. I've tried last commit 2b04e7c and noticed that the Display Preferences button does nothing.
No lines in the debug console when clicking it.

The command
`open /System/Library/PreferencePanes/Displays.prefPane`
in Terminal  works. It's the command saved as displayPrefPane variable
`static var displayPrefPane = "/System/Library/PreferencePanes/Displays.prefPane"`
and called in ViewControllerDisplays.swift
```swift
    @IBAction func openPrefsDispl(_ sender: Any) {
        _ = run("open " + initGlobVar.displayPrefPane)
    }
```

@matxpa fork has the same behaviour.
However, [Slice's fork ](https://github.com/CloverHackyColor/About-This-Hack)opens Display Preferences as expected.

**Comment by matxpa** [comment]
@perez987 

Hi
Yes you're right, but It happens only with en.lproj/Main.storyboard not with fr.lproj/Main.storyboard.

With a small modification in en.lproj/Main.storyboard the result is

![Capture d’écran 2023-10-24 à 21 56 49](https://github.com/0xCUB3/About-This-Hack/assets/70573409/fdaf3739-f529-48b7-ad78-9b3b4054f31b)

@0xCUB3 (en.lproj/Main.storyboard need to be modified and project too (fr.lproj/Main.storyboard is not activated (not added))
Modification is : to put Push Button Display Preferences... at the end of the list (and Displays at top)
placed on the middle "Push Button Display Preferences..." seems to be inhibited by "Display Name Center" area

![Capture d’écran 2023-10-24 à 22 00 57](https://github.com/0xCUB3/About-This-Hack/assets/70573409/5eb2ff0d-79a8-4444-9d23-ab064b99f6aa)

Regards

**Comment by perez987** [comment]
@matxpa 
Thanks for the explanation.

**Comment by perez987** [comment]
@matxpa 
You are right. Moving Display Preferences item to the end of the list fixes the issue.
In your enroll version the item is in last place. In the Slice fork it is in second to last place. That's why the issue was not present in both repos.
Thanks!!!

**Comment by perez987** [comment]
Closing the issue as resolved.
