### ISSUE TITLE
"Bootloader" section says "Apple UEFI" if Clover is used as a Bootloader

### ISSUE THREAD

**Issue by 5T33Z0** [0xCUB3/About-This-Hack#74]
&rarr; see Screenshot
![Clover](https://github.com/0xCUB3/About-This-Hack/assets/76865553/21af2758-de06-45b9-9acb-72ad59f8417b)

**Comment by matxpa** [comment]
@5T33Z0 @0xCUB3 @MDNich 

Hi
2 different reasons to get this behavior \: (but I'm certain you know below things)

  - 1) "/usr/local/bin/bdmesg" doesn't exist  (if so you D.L Clover_r5155.pkg, extract bdmesg from package and put bdmesg 
      in "/usr/local/bin" with sudo if user isn't admin. (and may be chmod 755))
      ls -l /usr/local/bin/bdmesg
      -rwxr-xr-x@ 1 xxxxxxx  staff  53664  9 avr  2023 /usr/local/bin/bdmesg

![Capture d’écran 2023-10-25 à 09 30 53](https://github.com/0xCUB3/About-This-Hack/assets/70573409/325e6282-f99c-4b7f-b574-fec500af60af)



  - 2) too much processor load and no time to execute bdmesg (Preview is displayed before bdmesg return a result) 
     it's the reason why we had to put Timers at different places to avoid this problem 
     Thread.sleep(forTimeInterval: n.m) to let creation of temporary DataFiles before trying extractions of some of their content. But here datas are extracted directly from Clover boot log content not from a Datafile but the behavior could be the same. 

May be other(s) reason(s) ? If someone knows ...

Regards

**Comment by 5T33Z0** [comment]
So, the "real" solution would be to integrate bdmsg in the app.

**Comment by maxpicelli** [comment]
Thank you guys, I appreciated that!
