### ISSUE TITLE
"Software Update..." not properly redirecting

### ISSUE THREAD

**Issue by nocontent06** [0xCUB3/About-This-Hack#77]
The "Software Update..." section in ATH doesn't redirect directly to the System Preference's "Software Updates". Instead it redirects to "General".

Thx m8

**Comment by 0xCUB3** [comment]
What version of macOS is this on...?

**Comment by nocontent06** [comment]
macOS Sonoma 14.1 on my MacPro6,1

**Comment by matxpa** [comment]
@nocontent06 

Hi
What does happen when you execute the command below in a Terminal window
open /System/Library/PreferencePanes/SoftwareUpdate.prefPane
Regards

**Comment by nocontent06** [comment]
Then the right Software Update Pane opens ;)

**Comment by matxpa** [comment]
@nocontent06 
Hi
"Then" with About This Hack or with Terminal command ?
Regards

**Comment by nocontent06** [comment]
With Terminal commands... so i think for versions 13.0+ you should use that Terminal Command :)

**Comment by matxpa** [comment]
@nocontent06 
Hi
Yes,but it's exactly the command used with ATH in ViewController.swift

    @IBAction func showSoftwareUpdate(_ sender: NSButton) {
        print("Software Update...")
        _ = run("open /System/Library/PreferencePanes/SoftwareUpdate.prefPane")
    }


With "Software Update..." Button i get this 

![Capture d’écran 2023-10-31 à 18 46 58](https://github.com/0xCUB3/About-This-Hack/assets/70573409/926a7a5a-f731-46cc-9dcf-965294c17574)

Regards

**Comment by nocontent06** [comment]
Okay... weird... i just need to wait about 30-45 Seconds... then it automatically redirects to "Software Update"

**Comment by matxpa** [comment]
Yes if you try with "About this Mac" you have to wait also (try and count)

**Comment by matxpa** [comment]
@0xCUB3  @nocontent06 
Hi
I think this issue (not really an issue) could be closed.
And the wait is longer when you click on "Displays Preferences..." button
Regards

**Comment by matxpa** [comment]
@0xCUB3 @MDNich 
Hi
This (not) issue must be closed.
Open (Apple) Software Update window with Ventura and Sonoma needs a long time (same thing with About this Mac)
Regards
