### ISSUE TITLE
I think the inbuilt-updater hasn't been fixed yet?

### ISSUE THREAD

**Issue by nocontent06** [0xCUB3/About-This-Hack#79]
<img width="260" alt="image" src="https://github.com/0xCUB3/About-This-Hack/assets/93335632/ab84e282-4461-4799-a959-fdd667d867e0">

**Comment by 0xCUB3** [comment]
this is because 1.0.0 introduced my own updater. 0.9.1 still uses the old one, which is why the new update doesn't show. Please search for old issues before posting your own; this is like the fifth time someone posted on this topic
