### ISSUE TITLE
When I click on Hackintosh Guide it opens Apple Help Home page

### ISSUE THREAD

**Issue by jzrodriguez98** [0xCUB3/About-This-Hack#83]
When I click on the Hackintosh Guide link in the support tab, it opens Apple Help Mac Basis webpage

https://help.apple.com/macos/big-sur/mac-basics/

**Comment by 0xCUB3** [comment]
Thank you for sharing this. I'll fix it in the next release 👍

**Comment by matxpa** [comment]
@0xCUB3 @jzrodriguez98

Hi
It's strange when i click on "Guide OC Hackintosh" it opens " OpenCore Install Guide" as you can see below

![Capture d’écran 2023-11-13 à 21 11 33](https://github.com/0xCUB3/About-This-Hack/assets/70573409/8a91ce39-0082-4383-b4c1-e5cbf47f5a5a)

![Capture d’écran 2023-11-13 à 21 11 58](https://github.com/0xCUB3/About-This-Hack/assets/70573409/cbddc6b0-f30c-449c-afff-a28b0010d371)

Regards

**Comment by matxpa** [comment]
@0xCUB3

Hi
It happens only with en.lproj/Main.storyboard (not with french one)
In v1.0.0 and v1.1.0 en.lproj/Main.storyboard see code lines 732, 737, 772 and 777.

Regards

**Comment by 0xCUB3** [comment]
got it; thanks.

**Comment by 0xCUB3** [comment]
Fixed with the latest commit.
