### ISSUE TITLE
GPU and Displays do not appear

### ISSUE THREAD

**Issue by Matgen84** [0xCUB3/About-This-Hack#84]
Hi @matxpa 

Despite your commits, GPU and Displays do not appear (my system: Ivybridge, SMBIOS macPro6,1, Monterey 12.7.1)

Can you take allok to the file attached, please.

Thanks

[ATH  Issue.txt](https://github.com/0xCUB3/About-This-Hack/files/13610210/ATH.Issue.txt)

**Comment by matxpa** [comment]
@Matgen84
Hi

Are you sur you use the V1.1.0 published at Nov. 11th ?
This question because the message below couldn't  be shown, output error is trapped ( nvram .... 2>/dev/null)
nvram: Error getting variable - '4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version': (iokit/common) data was not found.

Regards

**Comment by matxpa** [comment]
@Matgen84
We could suspect a timer problem between scr.txt file creation and OverView tab Display and GPU content filling.

As I told you on your #72 issue, if I use (all your files are linked (symbolic link) in /tmp/.ath ) your different ATH files provided on October 29.
A did it again today and the result of ATH v1.1.0 on my Ivy is : 

![Capture d’écran 2023-12-14 à 15 12 53](https://github.com/0xCUB3/About-This-Hack/assets/70573409/9cf6b5f9-1cfa-4d5d-9a18-c0626bfb5715)

![Capture d’écran 2023-12-14 à 15 13 11](https://github.com/0xCUB3/About-This-Hack/assets/70573409/4cc20c7a-d8aa-4214-bf23-068b9591e63f)

![Capture d’écran 2023-12-14 à 15 13 34](https://github.com/0xCUB3/About-This-Hack/assets/70573409/370cdf89-c548-40b1-9e64-397045c81089)

![Capture d’écran 2023-12-14 à 15 13 54](https://github.com/0xCUB3/About-This-Hack/assets/70573409/29c84585-ad67-44d4-80d2-ec53d7731748)

So ATH works fine, i'll send you a modified release with increased timer and we'll see what it'll do.
I'll build it with Xcode 14 on Monterey and try also, but not today.

Regards

**Comment by 0xCUB3** [comment]
@Matgen84 could you post an update?

**Comment by Matgen84** [comment]
Hi @0xCUB3 

I don't understand meaning "post an update" ! Despite @matxpa efforts and modified ATH (14/12/2023), the app don't work as it should be on my system (IvyBridge, Monterey, Clover Bootloader).

Below screenshots, text file.

Happy new year 
![Capture d’écran 2024-01-03 à 17 04 12](https://github.com/0xCUB3/About-This-Hack/assets/5956729/38441c21-b3f1-4ddb-bd39-f386b1894b33)


![Capture d’écran 2024-01-03 à 17 04 23](https://github.com/0xCUB3/About-This-Hack/assets/5956729/145a6a98-ecea-49e9-85ef-0e7f155e659b)


[Test _03:01:2024.txt](https://github.com/0xCUB3/About-This-Hack/files/13821150/Test._03.01.2024.txt)

**Comment by 0xCUB3** [comment]
@Matgen84 I am asking if you used the latest release, v1.1.0. Matxpa's modified release had other changes than my own release. Please verify.

**Comment by 0xCUB3** [comment]
Closing this issue due to negligence. If someone else has this same issue, they can create a new post.
