### ISSUE TITLE
About This Hack Not Work On macOS Ventura 13.1

### ISSUE THREAD

**Issue by malthiscode** [0xCUB3/About-This-Hack#9]
Im open about this hack on ventura and the app crash

**Comment by 0xCUB3** [comment]
Yeah unfortunately Apple blacklisted my app since I have too many downloads and I don't have a paid apple dev account. Sadly nothing that I can do. The only way for you to get the app to work at this point is to use Xcode to build it yourself. Sorry about that

**Comment by 0xCUB3** [comment]
@malthiscode Update: this release should fix everything. Let me know if it still doesn't work. Download it from here:
https://github.com/0xCUB3/About-This-Hack/releases/tag/0.6.0
You can thank @MDNich for debugging :)
