### ISSUE TITLE
The latest version is 404:NotFound. You are currently running 1.2.0.

### ISSUE THREAD

**Issue by matxpa** [0xCUB3/About-This-Hack#90]
@MDNich @0xCUB3

Hi
Can't found "https://raw.githubusercontent.com/0xCUB3/Website/main/content/ath.txt". Was this URL modified ?

![Capture d’écran 2024-04-29 à 17 27 52](https://github.com/0xCUB3/About-This-Hack/assets/70573409/b59ee09e-f4a3-4f95-a775-07e7dda22aca)

ON UpdateController.swift
static func checkForUpdates modifications you could do if you would
static func updateNotFound you could add if you would

    static func checkForUpdates() -> Bool {
        print("\(thisComponent) : Checking for updates...")
        _ = run("\(initGlobVar.curlLocation) -o \(initGlobVar.athtargetversionfile) \(initGlobVar.athsourceversionfile)")
        latestVersion = run("/usr/bin/tr -d '[:space:]' < \(initGlobVar.athtargetversionfile)")
        print("\(thisComponent) : between Local version (\(thisApplicationVersion)) and Remote version (\(latestVersion))")
 
       if !latestVersion.lowercased().contains("notfound") { //added

            if thisApplicationVersion < latestVersion {
                print("\(thisComponent) : Newer version (" + latestVersion + ") available")
                let prompt = alert(message: "Update found!", text: "The latest version is " + latestVersion + ". You are currently running " + thisApplicationVersion + ".")
                print("\(thisComponent) : Done")
                return prompt
            }

        } else {//added
            _ = updateNotFound(message: "Update NOT FOUND", text: "Returned Error on latest version search  \n(\(latestVersion))")
        }
        return false
    }
    
    static func alert...
    }

    static func updateNotFound(message: String, text: String) -> Bool {//added
        let alert = NSAlert()
        alert.messageText = message
        alert.informativeText = text
        alert.alertStyle = .critical
        alert.addButton(withTitle: "Return")
        return alert.runModal() == NSApplication.ModalResponse.alertFirstButtonReturn
    }

![Capture d’écran 2024-04-30 à 19 07 27](https://github.com/0xCUB3/About-This-Hack/assets/70573409/6493eade-37d0-4356-b8e0-6b50cd8920e3)

Regards

**Comment by matxpa** [comment]
Otherwise 

1) Add a variable in InitGlobalVariables.swift
    static var defaultfileManager      = FileManager.default

2) Add a function (where you want)
func doesFileExist(absolutePath: String) -> Bool {
    var isDirectory: ObjCBool = false
    return (initGlobVar.defaultfileManager.fileExists(atPath: absolutePath, isDirectory: &isDirectory))
}

3) Check if latest version file exists (in UpdateController.swift)
         if doesFileExist(absolutePath: "\(initGlobVar.athsourceversionfile)") { // added
            print("\(thisComponent) : Checking for updates...")
            _ = run("\(initGlobVar.curlLocation) -o \(initGlobVar.athtargetversionfile) \(initGlobVar.athsourceversionfile)")
            latestVersion = run("/usr/bin/tr -d '[:space:]' < \(initGlobVar.athtargetversionfile)")
            print("\(thisComponent) : between Local version (\(thisApplicationVersion)) and Remote version (\(latestVersion))")
            if !latestVersion.lowercased().contains("notfound") {
                if thisApplicationVersion < latestVersion {
                    print("\(thisComponent) : Newer version (" + latestVersion + ") available")
                    let prompt = alert(message: "Update found!", text: "The latest version is " + latestVersion + ". You are currently running " + thisApplicationVersion + ".")
                    print("\(thisComponent) : Done")
                    return prompt
                }
            } else {
                print("\(thisComponent) : Update NOT FOUND : Returned Error on latest version search\n\(initGlobVar.athsourceversionfile) (\(latestVersion))")
                _ = updateNotFound(message: "Update NOT FOUND", text: "Returned Error on latest version search\n(\(latestVersion))")
            }
        } else { // added
            print("\(thisComponent) : Latest Version File couldn't be found : \(initGlobVar.athsourceversionfile)")
            _ = updateNotFound(message: "Latest Version File couldn't be found", text: "\(initGlobVar.athsourceversionfile)")
        }
        return false
    }

![Capture d’écran 2024-05-01 à 16 14 01](https://github.com/0xCUB3/About-This-Hack/assets/70573409/cd1d99e0-6f36-494c-b223-a6af47ed27aa)

Regards

**Comment by 0xCUB3** [comment]
the reason why it's not found is because I deleted my website. I honestly forgot that this file was in there...
I will make a new one once I make the next release.

**Comment by 0xCUB3** [comment]
it should be resolved now.
