### ISSUE TITLE
Code signature changed?

### ISSUE THREAD

**Issue by AmnaSN** [0xCUB3/About-This-Hack#93]
In the latest version 1.2.0 of About-this-hack, the code signature is 'Apple Development: alexanderskula@icloud.com (59HZ89X5NN)' instead of 'Boaz Hecht (ANH32X67FF)'. Can you please confirm if this change is legitimate?

**Comment by 0xCUB3** [comment]
yes. In the previous version, I had someone with the pro developer license sign the app, but they are no longer available to sign the app, so we have to use my free license.

**Comment by core-code** [comment]
note that GateKeeper prevents launching of apps signed with non-DeveloperID signatures by default, so you might need to provide some instructions how to get the app opened

**Comment by MDNich** [comment]
It is already in the readme @core-code:

https://github.com/0xCUB3/About-This-Hack?tab=readme-ov-file#how-to-install

**Comment by 0xCUB3** [comment]
Yeah there are instructions at the bottom of the repo

**Comment by core-code** [comment]
ah great, thanks!
