### ISSUE TITLE
Displays an incorrect display configuration 

### ISSUE THREAD

**Issue by Fischmuetze** [0xCUB3/About-This-Hack#99]
This is the real config
![true](https://github.com/0xCUB3/About-This-Hack/assets/19834496/c9720a10-1953-4ba4-87a4-329640b5c963)

The configuration displayed by the app
![false](https://github.com/0xCUB3/About-This-Hack/assets/19834496/07698c43-9140-4cfa-9341-7f6274042b7a)

**Comment by 0xCUB3** [comment]
Thanks for bringing this up. Unfortunately, there's no way (that I know of) to pull the exact display configuration (I'm assuming that's what you are referring to - where the monitors are placed with respect to each other), so I don't think this is a fixable issue. Perhaps @matxpa played around with this in his fork, but I wouldn't keep my fingers crossed. 

On the other hand, it looks like the middle text stretches out too wide! Something else to fix for the next bug fix release :)

**Comment by Fischmuetze** [comment]
Hi,
thank you for the quick response.
I don't mean the arrangement of the monitors. I mean ether more the description (name) of the monitors and their allocated resolution data. As you can see I have a built-in Retina display with high res (3024x1964) and 2x Dell monitors (2560x1440).
But "About-This-Hack" mixed that wrong and shows the resolution data of the MacBook Pro built-in Retina display as "Color display" and for the built-in Retina display the resolution data of the Dell monitor. Also the name of the second monitor isn't displayed as Dell (instead it shows  Color LCD.

Maybe just as hint - This app project is able to show my configuration correct
https://github.com/MonitorControl/MonitorControl

**Comment by 0xCUB3** [comment]
I'll look into monitorcontrol's method. For some reason, displays are weird in that apple randomly renames them sometimes in the "System Information" app (which is where we basically pull our data from). At this point, I'm not sure there's a way around it, but if MonitorControl can do it, we might be able to do it too.
